sudo: required

services:
  - docker

language: go

notifications:
  email: true

go:
  - 1.7

env:
  global:
  - ETCD_VERSION=3.0.13
  - K8S_VERSION=1.4.5

before_install:
  - sudo bash -c 'sysctl net.ipv6.conf.all.disable_ipv6=0'
  - sudo bash -c 'sysctl net.ipv6.conf.default.disable_ipv6=0'
  - sudo bash -c 'sysctl net.ipv6.conf.lo.disable_ipv6=0'
  - sudo mkdir -p /ingress-controller/ssl
  - sudo chmod 777 -R /ingress-controller

install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:  
  - make fmt lint vet cover
  - RELEASE="ci-$TRAVIS_BUILD_ID" make -c backend/nginx container push
  - RELEASE="ci-$TRAVIS_BUILD_ID" BACKENDS=nginx make e2e
