language: go

sudo: false

notifications:
  email: true

go:
  - 1.6
  - 1.7
  - tip

install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - make build vet lint fmt test cover
